[[constraint]]
  name = "github.com/hashicorp/hcl2"
  branch = "master"

[[constraint]]
  name = "github.com/zclconf/go-cty"
  branch = "master"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "15"
